const WORLD_SIZE=1e9;
const INITIAL_SHIP_HEALTH=10;
const SHIP_SPEED=10;
const SHIP_SIZE=10;
const MAX_TURN_RATE=60;
const TURN_RATE_=5;

const INITIAL_GOLD=0;
const INITIAL_CANNONBALLS=10;
const CANNON_DAMAGE=2;
const CANNON_RANGE=1e6;
const CANNON_COST=1;
const CANNON_WAIT_TIME=5;
const MIN_LOOT=1;
const MAX_LOOT=10;
const LOOT_SIZE=10;
